'use client';

import { useState } from 'react';
import { WizardShell } from '../wizard-shell';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent } from '@/components/ui/card';
import { Goal, LeadIndicator, Json } from '@/lib/types/database';

interface HabitItem {
  goal_id: string | null;
  name: string;
  cue: string;
  location: string;
  tracking_type: 'binary' | 'count' | 'time';
  weekly_target: number;
  minimum_version: string;
}

interface HabitsStepProps {
  stepId: string;
  initialData: Json;
  goals: Goal[];
  leadIndicators: LeadIndicator[];
}

export function HabitsStep({ stepId, initialData, goals, leadIndicators }: HabitsStepProps) {
  const data = initialData as Record<string, unknown>;
  
  const [createFromIndicators, setCreateFromIndicators] = useState<string>(
    (data.create_from_indicators as string) || 'yes'
  );
  const [habits, setHabits] = useState<HabitItem[]>(
    (data.habits as HabitItem[]) || []
  );

  const addHabit = () => {
    if (habits.length < 12) {
      setHabits([...habits, {
        goal_id: null,
        name: '',
        cue: '',
        location: '',
        tracking_type: 'binary',
        weekly_target: 3,
        minimum_version: '',
      }]);
    }
  };

  const removeHabit = (index: number) => {
    setHabits(habits.filter((_, i) => i !== index));
  };

  const updateHabit = (index: number, field: keyof HabitItem, value: unknown) => {
    setHabits(habits.map((h, i) => 
      i === index ? { ...h, [field]: value } : h
    ));
  };

  // Auto-generate habits from lead indicators if selected
  const autoGeneratedHabits = createFromIndicators === 'yes' 
    ? leadIndicators.map(li => ({
        goal_id: li.goal_id,
        name: li.name,
        cue: '',
        location: '',
        tracking_type: li.measure_type as 'binary' | 'count' | 'time',
        weekly_target: li.weekly_target,
        minimum_version: li.minimum_version || '',
      }))
    : [];

  const allHabits = [...autoGeneratedHabits, ...habits];

  const formData = {
    create_from_indicators: createFromIndicators,
    habits: allHabits.filter(h => h.name.trim()),
  };

  return (
    <WizardShell
      stepId={stepId}
      initialData={initialData}
      formData={formData}
      canProceed={true}
    >
      <div className="space-y-8">
        {/* Auto-create from Lead Indicators */}
        {leadIndicators.length > 0 && (
          <div className="space-y-4">
            <Label className="text-base font-medium">
              Turn lead indicators into habits?
            </Label>
            <p className="text-sm text-muted-foreground">
              You defined {leadIndicators.length} lead indicator(s). These can become trackable habits.
            </p>
            
            <RadioGroup
              value={createFromIndicators}
              onValueChange={setCreateFromIndicators}
              className="space-y-2"
            >
              <div className="flex items-center space-x-3 p-3 rounded-lg border border-border hover:bg-accent/50">
                <RadioGroupItem value="yes" id="yes" />
                <Label htmlFor="yes" className="cursor-pointer flex-1">
                  Yes, auto-create habits from lead indicators
                </Label>
              </div>
              <div className="flex items-center space-x-3 p-3 rounded-lg border border-border hover:bg-accent/50">
                <RadioGroupItem value="no" id="no" />
                <Label htmlFor="no" className="cursor-pointer flex-1">
                  No, I&apos;ll create habits manually
                </Label>
              </div>
            </RadioGroup>
          </div>
        )}

        {/* Auto-generated habits preview */}
        {createFromIndicators === 'yes' && autoGeneratedHabits.length > 0 && (
          <div className="space-y-3">
            <Label className="text-sm text-muted-foreground">
              Auto-generated habits from lead indicators:
            </Label>
            <div className="grid gap-2">
              {autoGeneratedHabits.map((habit, i) => {
                const goal = goals.find(g => g.id === habit.goal_id);
                return (
                  <div key={i} className="p-3 rounded-lg bg-accent/30 flex justify-between items-center">
                    <span>{habit.name}</span>
                    <span className="text-xs text-muted-foreground">{goal?.title}</span>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Manual Habits */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <Label className="text-base font-medium">
                Additional habits (0-12)
              </Label>
              <p className="text-sm text-muted-foreground">
                Add any other habits you want to track.
              </p>
            </div>
            {habits.length < 12 && (
              <Button variant="outline" size="sm" onClick={addHabit}>
                + Add habit
              </Button>
            )}
          </div>

          {habits.map((habit, index) => (
            <Card key={index} className="border-border">
              <CardContent className="pt-4 space-y-4">
                <div className="flex items-start justify-between">
                  <div className="flex-1 space-y-4">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label>Habit name</Label>
                        <Input
                          value={habit.name}
                          onChange={(e) => updateHabit(index, 'name', e.target.value)}
                          placeholder="e.g., Meditate, Read, Exercise"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label>Link to goal (optional)</Label>
                        <Select
                          value={habit.goal_id || 'none'}
                          onValueChange={(v) => updateHabit(index, 'goal_id', v === 'none' ? null : v)}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="None" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="none">None</SelectItem>
                            {goals.map(g => (
                              <SelectItem key={g.id} value={g.id}>{g.title}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label>Cue / trigger</Label>
                        <Input
                          value={habit.cue}
                          onChange={(e) => updateHabit(index, 'cue', e.target.value)}
                          placeholder="e.g., After coffee, At 7:30am"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label>Where? (optional)</Label>
                        <Input
                          value={habit.location}
                          onChange={(e) => updateHabit(index, 'location', e.target.value)}
                          placeholder="e.g., Living room, Office"
                        />
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <div className="space-y-2">
                        <Label>Tracking type</Label>
                        <Select
                          value={habit.tracking_type}
                          onValueChange={(v) => updateHabit(index, 'tracking_type', v)}
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="binary">Binary (did/didn&apos;t)</SelectItem>
                            <SelectItem value="count">Count</SelectItem>
                            <SelectItem value="time">Time</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="space-y-2">
                        <Label>Weekly target</Label>
                        <Input
                          type="number"
                          value={habit.weekly_target}
                          onChange={(e) => updateHabit(index, 'weekly_target', parseInt(e.target.value) || 0)}
                          min={0}
                          max={100}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label>Minimum version</Label>
                        <Input
                          value={habit.minimum_version}
                          onChange={(e) => updateHabit(index, 'minimum_version', e.target.value)}
                          placeholder="e.g., 2 minutes"
                        />
                      </div>
                    </div>
                  </div>
                  
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => removeHabit(index)}
                    className="text-destructive ml-2"
                  >
                    ×
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}

          {habits.length === 0 && (
            <p className="text-sm text-muted-foreground text-center py-4">
              No additional habits added. Click &quot;Add habit&quot; to create one.
            </p>
          )}
        </div>
      </div>
    </WizardShell>
  );
}

